### ISSUE TITLE
Invalid numeric literal 

### ISSUE THREAD

**Issue by contactabhay** [IvanGlinkin/Domain_checker#2]
[ < ] Enter the domain name: bmc.com
[ + ] Domain name bmc.com exists. Start enumerating...

[ + ] IP address is 204.74.99.100
[ > ] Checking for subdomains...
parse error: Invalid numeric literal at line 1, column 10
host: '' is not a legal name (unexpected end of input)

**Comment by AlexFromMoscow6** [comment]
@IvanGlinkin same problem - parse error: Invalid numeric literal at line 1, column 7

**Comment by IvanGlinkin** [comment]
Hi mates,
Understood. Will fix that ASAP.
Regards, Ivan

**Comment by AlexFromMoscow6** [comment]
@IvanGlinkin thank you! We will wait

**Comment by IvanGlinkin** [comment]
Fixed, guys.
The issue was in https://crt.sh domain through which we were getting subdomains.
Changed into another web-site. Did it as a quick fix hence it's a little bit messy in the code. But it's working and it's more important :)
<img width="1168" alt="Screenshot 2023-03-12 at 00 11 39" src="https://user-images.githubusercontent.com/64857726/224511799-95c3b465-40c3-4809-94da-9418b42ff7c4.png">

**Comment by AlexFromMoscow6** [comment]
@IvanGlinkin thank you! It's working now
